# Generated by Django 5.2.4 on 2025-08-05 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "creator",
                    models.CharField(
                        default="system",
                        help_text="Имя пользователя создавшего привычку (для публичных привычек)",
                        max_length=200,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "place",
                    models.CharField(help_text="Место выполнения привычки.", max_length=200, verbose_name="Место"),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        help_text="Действие, которое представляет собой привычку.", verbose_name="Действие"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, является ли привычка приятной (True) или полезной (False).",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания в днях. "
                                  "Например, 1 - ежедневно, 7 - раз в неделю)",
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True, help_text="Укажите вознаграждение", null=True, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "time_complete",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Время, за которое необходимо выполнить привычку (в секундах).",
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                (
                    "sign_publicity",
                    models.BooleanField(
                        default=False,
                        help_text="Привычки можно публиковать в общий доступ, "
                                  "чтобы другие пользователи могли брать в пример чужие привычки.",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная привычка (важно указывать для полезных привычек, но не для приятных).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
