# Generated by Django 5.2.4 on 2025-08-07 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_execution_date",
            field=models.DateField(
                blank=True,
                help_text="Дата последнего выполнения привычки.",
                null=True,
                verbose_name="Дата последнего выполнения",
            ),
        ),
    ]
